//  切换导航栏显示隐藏
export const SET_TOGGLE_NAV = 'SET_TOGGLE_NAV';

export const SET_TOGGLE_SELECT_FONT = 'SET_TOGGLE_SELECT_FONT';

export const SET_TOGGLE_MODE = 'SET_TOGGLE_MODE';

export const SET_CURRENT_COLOR = 'SET_CURRENT_COLOR';

export const ADD_FONT_SIZE = 'ADD_FONT_SIZE';

export const SUB_FONT_SIZE = 'SUB_FONT_SIZE';

export const SET_FONT_SIZE = 'SET_FONT_SIZE';

export const PREV_CHAPTER = 'PREV_CHAPTER';

export const NEXT_CHAPTER = 'NEXT_CHAPTER';

export const SET_CURRENT_CHAPTER = 'SET_CURRENT_CHAPTER';

export const SET_MAX_CHAPTER = 'SET_MAX_CHAPTER';